export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const SAVE_USER_PAYMENT_REQUEST = 'SAVE_USER_PAYMENT_REQUEST';
export const SAVE_USER_PAYMENT_SUCCESS = 'SAVE_USER_PAYMENT_SUCCESS';
export const SAVE_USER_PAYMENT_FAILURE = 'SAVE_USER_PAYMENT_FAILURE';
